# setup.py — First-time setup wizard for Interceptr
from __future__ import annotations

import os
import sys
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

console = Console()

CONFIG_DIR = Path.home() / ".interceptr"
CONFIG_FILE = CONFIG_DIR / ".env"

_MODELS = {
    "openai": "gpt-4o-mini",
    "anthropic": "claude-haiku-4-5-20251001",
    "google": "gemini-1.5-flash",
}

_PROVIDER_LABELS = {
    "1": ("openai", "OpenAI"),
    "2": ("anthropic", "Anthropic"),
    "3": ("google", "Google"),
}


def is_first_run() -> bool:
    """Return True if ~/.interceptr/.env does not exist."""
    return not CONFIG_FILE.exists()


def _ask_with_timeout(prompt: str, default: str = "n", timeout: int = 30) -> str:
    """Ask a yes/no question with a timeout; returns default if timeout or non-TTY."""
    if not sys.stdin.isatty():
        return default
    try:
        import signal

        def _handler(signum, frame):
            raise TimeoutError

        signal.signal(signal.SIGALRM, _handler)
        signal.alarm(timeout)
        try:
            answer = Prompt.ask(f"{prompt} [dim](30s timeout)[/dim]", default=default, console=console)
        finally:
            signal.alarm(0)
        return answer
    except TimeoutError:
        console.print("\n[dim]No response — continuing with regex-only detection.[/dim]")
        return default


def _save_config(provider: str | None, api_key: str | None, model: str | None) -> None:
    """Write ~/.interceptr/.env with appropriate variables."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Interceptr configuration",
        "# Generated by interceptr setup — do not share this file",
        "",
        "INTERCEPTR_INITIALIZED=true",
    ]

    if provider and api_key and model:
        lines.append("INTERCEPTR_DETECTION_MODE=llm")
        lines.append("")
        lines.append(f"INTERCEPTR_LLM_PROVIDER={provider}")
        lines.append(f"INTERCEPTR_LLM_MODEL={model}")
        lines.append(f"INTERCEPTR_LLM_API_KEY={api_key}")
    else:
        lines.append("INTERCEPTR_DETECTION_MODE=regex")

    CONFIG_FILE.write_text("\n".join(lines) + "\n")
    CONFIG_FILE.chmod(0o600)


def run_setup() -> None:
    """Run the interactive first-time setup wizard."""
    # Step 1 — Welcome panel
    console.print(
        Panel(
            "Welcome to Interceptr\n"
            "AI Agent Security Middleware by Kelink\n\n"
            "Let's get you set up. This will only take a moment.",
            border_style="green",
        )
    )

    # Step 2 — Explain prompt injection detection
    console.print(
        Panel(
            "Prompt Injection Detection\n\n"
            "Interceptr protects your agents using a curated regex pattern library.\n"
            "This works completely offline, costs $0, and catches the vast majority\n"
            "of known prompt injection attacks.\n\n"
            "Want stronger protection? You can optionally provide an API key from\n"
            "an AI provider to add an LLM-powered detection layer on top of regex.\n"
            "Requests will be analyzed by the model at your own cost.",
            border_style="cyan",
        )
    )

    # Step 3 — Ask if they want to add a provider
    answer = _ask_with_timeout(
        "Would you like to add an AI provider for enhanced detection? [y/N]",
        default="n",
        timeout=30,
    )

    provider = None
    api_key = None
    model = None

    if answer.lower() in ("y", "yes"):
        # Step 4 — Provider selection
        console.print(
            "\nChoose a provider:\n"
            "  [bold][1][/bold] OpenAI    (model: gpt-4o-mini)\n"
            "  [bold][2][/bold] Anthropic (model: claude-haiku-4-5-20251001)\n"
            "  [bold][3][/bold] Google    (model: gemini-1.5-flash)"
        )

        choice = Prompt.ask("Enter choice", choices=["1", "2", "3"], console=console)
        provider_key, provider_label = _PROVIDER_LABELS[choice]
        model = _MODELS[provider_key]

        # Ask for API key (hidden, max 3 attempts)
        for attempt in range(3):
            key = Prompt.ask("Enter your API key", password=True, console=console)
            if key.strip():
                provider = provider_key
                api_key = key.strip()
                break
            remaining = 2 - attempt
            if remaining > 0:
                console.print(f"[yellow]API key cannot be empty. {remaining} attempt(s) left.[/yellow]")
            else:
                console.print("[yellow]No valid key provided — falling back to regex-only detection.[/yellow]")
                provider = None
                api_key = None
                model = None

    # Step 5 — Save configuration
    _save_config(provider, api_key, model)

    # Step 6 — Confirmation panel
    if provider and model:
        provider_label = _PROVIDER_LABELS[
            next(k for k, (p, _) in _PROVIDER_LABELS.items() if p == provider)
        ][1]
        console.print(
            Panel(
                f"[green]✅ Setup complete — using {provider_label} ({model}) + regex detection[/green]\n\n"
                "You can change this anytime with: [bold]interceptr config[/bold]",
                border_style="green",
            )
        )
    else:
        console.print(
            Panel(
                "[green]✅ Setup complete — using regex detection (offline, $0)[/green]\n\n"
                "You can change this anytime with: [bold]interceptr config[/bold]",
                border_style="green",
            )
        )
